steps:
 

  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/gkemedium/ethereum/getlastblocknumber-image', '.']
    env:
      - 'REGION=europe-west1'

  # Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/gkemedium/ethereum/getlastblocknumber-image']
    env:
      - 'REGION=europe-west1'

   # Deploy the image as a Cloud Run job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'beta'
      - 'run'
      - 'jobs'
      - '${' + ('1' if `echo $${_CHECK_JOB_EXISTS} | grep -q "ERROR:"; echo $$?` else '2') + '}'  # If job exists, use 'update', else use 'create'
      - 'publishlatestblocknumbertopubsub'
      - '--image=europe-west1-docker.pkg.dev/gkemedium/ethereum/getlastblocknumber-image'
      - '--region=europe-west1'
      - '--set-env-vars=PROJECT_ID=$PROJECT_ID,PROJECT_NUMBER=$PROJECT_NUMBER'

timeout: 600s