steps:
 

  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/gkemedium/ethereum/getlastblocknumber-image', '.']
    env:
      - 'REGION=europe-west1'

  # Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/gkemedium/ethereum/getlastblocknumber-image']
    env:
      - 'REGION=europe-west1'

   # Deploy the image as a Cloud Run job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'beta'
      - 'run'
      - 'jobs'
      - 'create'
      - 'publishlatestblocknumbertopubsub'
      - '--image=europe-west1-docker.pkg.dev/gkemedium/ethereum/getlastblocknumber-image'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--set-env-vars=PROJECT_ID=$PROJECT_ID'

timeout: 600s